project:
  type: website
  output-dir: docs

website:
  title: "Olivia Zhang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Selected Publications

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
